- import_tasks: go.yaml
- import_tasks: build.yaml
- name: Install Minio command-line
  ansible.builtin.get_url:
    dest: /usr/local/bin/mc
    url: "https://dl.min.io/client/mc/release/linux-amd64/mc"
    mode: "0755"
  become: true
  become_user: root
- name: reStart Minio
  ansible.builtin.systemd_service:
    name: minio
    state: restarted
    enabled: true
  become: true
  become_user: root
