services:
  web:
    image: nginx:latest
    ports: 
      - "80:80"
    networks:
      - default
    volumes:
      - shared-volume:/usr/share/nginx/html
    depends_on:
      - hello

  hello:
    image: almalinux:10
    command: '/bin/sleep 1000000000000'
    networks: 
      - default
    volumes:
      - shared-volume:/data

networks:
  default:
    driver: bridge

volumes:
  shared-volume:

