- name: Stop client service if it is running.
  ansible.builtin.systemd_service:
    name: beegfs-client
    state: stopped
    enabled: false
  become: true
  become_user: root
  ingore_errors: true
- name: Create mount location
  ansible.builtin.file:
    path: /beegfs
    state: directory
  become: true
  become_user: root
- name: Configure client
  ansible.builtin.command:
    cmd: /opt/beegfs/sbin/beegfs-setup-client -m mgmtnode
  become: true
  become_user: root
- name: Mounts file
  ansible.builtin.copy:
    src: files/beegfs-mounts.conf
    dest: /etc/beegfs/beegfs-mounts.conf
    owner: root
    group: root
  become: true
  become_user: root
- name: start client
  ansible.builtin.systemd_service:
    name: beegfs-client
    state: started
    enabled: true
  become: true
  become_user: root
- name: Make user directory
  ansible.builtin.file:
    path: /beegfs/almalinux
    state: directory
    owner: almalinux
  become: true
  become_user: root
- name: Create home directory sym-link
  ansible.builtin.file:
    src: /beegfs/almalinux
    dest: "/home/almalinux/beegfsüêù"
    state: link
